name: release

# trigger on published release
on:
  release:
    types: [published]

jobs:
  load_supported_versions:
    runs-on: ubuntu-20.04

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Save supported versions as output
        id: set-matrix
        run: |
          SUPPORTED_VERSIONS=$(cat ./supported_versions.json)
          SUPPORTED_VERSIONS="${SUPPORTED_VERSIONS//'%'/%25}"
          SUPPORTED_VERSIONS="${SUPPORTED_VERSIONS//$'\n'/%0A}"
          SUPPORTED_VERSIONS="${SUPPORTED_VERSIONS//$'\r'/%0D}"
          echo "::set-output name=matrix::${SUPPORTED_VERSIONS}"

  build_push_release:
    runs-on: ubuntu-20.04
    needs: load_supported_versions

    strategy:
      matrix: ${{ fromJSON(needs.load_supported_versions.outputs.matrix) }}

    env:
      REGISTRY: docker.io
      ORGANIZATION: "davidvpe"
      IMAGE_NAME: "terraform-aws-cli"

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get and save the release tag
        run: echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and save the image release tag
        run: echo "IMAGE_TAG=release-${RELEASE_TAG}_terraform-${{ matrix.tf_version }}_awscli-${{ matrix.awscli_version }}" >> $GITHUB_ENV

      - name: Build image
        run: docker image build . --file Dockerfile --build-arg TERRAFORM_VERSION=${{ matrix.tf_version }} --build-arg AWS_CLI_VERSION=${{ matrix.awscli_version }} --tag ${ORGANIZATION}/${IMAGE_NAME}:${IMAGE_TAG}

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to registry
        run: docker push ${ORGANIZATION}/${IMAGE_NAME}:${IMAGE_TAG}

      - name: Save image
        run: docker image save -o ${IMAGE_NAME}-${IMAGE_TAG}.tar ${ORGANIZATION}/${IMAGE_NAME}:${IMAGE_TAG}

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}
          path: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}.tar
